services:
  db:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outbox_demo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/outbox_demo
      WORKER_CHAOS: ${WORKER_CHAOS:-0}
      SEED_DATA: ${SEED_DATA:-false}
      SEED_COUNT: ${SEED_COUNT:-50}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: 1
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
